# Generated by Django 4.0.5 on 2022-08-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_deposit_expense_income_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('num_of_products', models.IntegerField()),
            ],
        ),
    ]
