# Generated by Django 4.0.5 on 2022-08-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
