# Generated by Django 4.0.5 on 2022-08-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0005_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deposit',
        ),
    ]
