# Generated by Django 4.0.5 on 2022-08-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0008_kpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='amount',
            field=models.FloatField(),
        ),
    ]
